### ISSUE TITLE
Can't kill run without killing sbt too

### ISSUE THREAD

**Issue by don41382** [loicdescotte/pureWebappSample#1]
It's not possible to kill/stop the app from sbt without killing sbt too.

``` sbt:pureWebAppSample> run ```

Any ideas?

**Comment by don41382** [comment]
I found the project ```sbt-resolver```. It allows stopping and automatically restarting of the application. 

see https://github.com/spray/sbt-revolver

Wdyt?

**Comment by loicdescotte** [comment]
I think it's related to http4s and sbt, not really to this example project?

**Comment by don41382** [comment]
Good point. And as mentioned, ```sbt-revolver``` is a good solution for this. But I am not sure if we should add this as a plugin.

Closing for now.
