### ISSUE TITLE
App crashes, when a not existing stock id is chosen

### ISSUE THREAD

**Issue by don41382** [loicdescotte/pureWebappSample#2]
When you call an HTTP-GET on ```http://localhost:8080/stock/5``` an SQL error occurs due to the fact, that an empty result is returned.

**Error**
```ResultSet exhausted; more rows expected```

**Response**
```json
{
"Error": "org.h2.jdbc.JdbcSQLException: Table \"STOCK\" already exists; SQL statement:\nCREATE TABLE stock\r\n(\r\n    id INT NOT NULL AUTO_INCREMENT,\r\n    value INT NOT NULL,\r\n    PRIMARY KEY(id)\r\n) [42101-196]"
}```

It looks like the transactor driver manager restarts and tries to re-run the ```create.sql`` even though the database was not reseted.

**Comment by loicdescotte** [comment]
I've seen this indeed, I'm trying to find a solution. Thanks for opening the issue :)

**Comment by loicdescotte** [comment]
First part fixed,
it was related to h2 in memory db and the db init being part of the jdbc url.
Still unable to display the right error , working on it :)

**Comment by loicdescotte** [comment]
fixed  :)
